
language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7
                      - cmake
                      - liblua5.2-dev
                      - zlib1g-dev
                        # Boost and SDL2 library versions provided are too old, they must be compiled manually.
        - os: osx
          compiler: clang

cache:
    directories:
        - $HOME/.ccache
        - $HOME/download

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      brew update &&
      brew upgrade cmake boost &&
      brew install sdl2 sdl2_ttf sdl2_image sdl2_mixer lua;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . "$TRAVIS_BUILD_DIR/.travis/before_install.sh"; fi 

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . "$TRAVIS_BUILD_DIR/.travis/install.sh"; fi

script: 
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ccache --show-stats; fi

notifications:
    email: false
