
language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          compiler: gcc-7
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7
                      - cmake
                      - liblua5.2-dev
                      - zlib1g-dev
                        # Boost and SDL2 library versions provided are too old, they must be compiled manually.
        - os: osx
          compiler: clang

cache:
    directories:
        - $HOME/.ccache
        - $HOME/download

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update &&
      brew upgrade cmake boost &&
      brew install sdl2 sdl2_ttf sdl2_image sdl2_mixer lua;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       export CC="gcc-7";
       export CXX="g++-7";
       gcc -v && g++ -v;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . "$TRAVIS_BUILD_DIR/.travis/before_install.sh"; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       export CC="gcc-7";
       export CXX="g++-7";
       gcc -v && g++ -v;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . "$TRAVIS_BUILD_DIR/.travis/install.sh"; fi

script:
  - cd "$TRAVIS_BUILD_DIR"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       export CC="gcc-7";
       export CXX="g++-7";
       export LD_LIBRARY_PATH="/usr/lib:$LD_LIBRARY_PATH";
       export LD_RUN_PATH="/usr/lib:$LD_RUN_PATH";
       export CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=TRUE";
       gcc -v && g++ -v;
    fi
  - env
  - cd deps
  - wget --no-verbose "http://ylvania.style.coocan.jp/file/elona122.zip"
  - unzip elona122.zip
  - rm elona122.zip
  - cd ..
  - make VERBOSE=1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ccache --show-stats; fi
  - pwd
  - ls
  - cd ElonaFoobar
  - pwd
  - ls
  - cd bin
  - pwd
  - ls
  - ./test_runner

notifications:
    email: false
