shallow_clone: true
clone_folder: C:\projects\ElonaFoobar

os:
  - Visual Studio 2017

environment:
  matrix:
  - CMAKE_ARGS: -G "Visual Studio 15 2017 Win64"
    BOOST_VERSION: 1.66.0
    BOOST_ROOT: C:\Libraries\boost_1_66_0
    PREFIX: C:\SDK

build:
  verbosity: detailed

configuration:
  - Debug


# for master branch
for:
-
  branches:
    only:
      - master

  configuration:
    - Release


branches:
  except:
    - /pr\/.+/

cache:
  C:\SDK -> appveyor.yml

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - cd C:\projects\ElonaFoobar
  - if exist %PREFIX% set NEEDDEPENDS=rem

  - |-
    %NEEDDEPENDS% mkdir %PREFIX%\include\SDL2
    %NEEDDEPENDS% mkdir %PREFIX%\lib
    %NEEDDEPENDS% cd %TEMP%

  - |-
    %NEEDDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
    %NEEDDEPENDS% 7z x SDL2-devel-2.0.8-VC.zip > nul
    %NEEDDEPENDS% copy SDL2-2.0.8\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy SDL2-2.0.8\lib\x64\* %PREFIX%\lib > nul
  - |-
    %NEEDDEPENDS% appveyor DownloadFile http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.2-VC.zip
    %NEEDDEPENDS% 7z x SDL2_mixer-devel-2.0.2-VC.zip > nul
    %NEEDDEPENDS% copy SDL2_mixer-2.0.2\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy SDL2_mixer-2.0.2\lib\x64\* %PREFIX%\lib > nul
  - |-
    %NEEDDEPENDS% appveyor DownloadFile https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-VC.zip
    %NEEDDEPENDS% 7z x SDL2_ttf-devel-2.0.14-VC.zip > nul
    %NEEDDEPENDS% copy SDL2_ttf-2.0.14\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy SDL2_ttf-2.0.14\lib\x64\* %PREFIX%\lib > nul
  - |-
    %NEEDDEPENDS% appveyor DownloadFile http://downloads.sourceforge.net/luabinaries/lua-5.3.4_Win64_vc14_lib.zip
    %NEEDDEPENDS% 7z x lua-5.3.4_Win64_vc14_lib.zip -olua53 > nul
    %NEEDDEPENDS% copy lua53\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy lua53\* %PREFIX%\lib > nul
  - |-
    %NEEDDEPENDS% appveyor DownloadFile http://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.3-VC.zip
    %NEEDDEPENDS% 7z x SDL2_image-devel-2.0.3-VC.zip > nul
    %NEEDDEPENDS% copy SDL2_image-2.0.3\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy SDL2_image-2.0.3\lib\x64\* %PREFIX%\lib > nul

build_script:
  - chcp 65001
  - cd %PREFIX%
  - appveyor DownloadFile http://ylvania.style.coocan.jp/file/elona122.zip
  - 7z x elona122.zip > nul
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir bin
  - cd bin
  - cmake -DCMAKE_PREFIX_PATH=%PREFIX% -DWITH_TESTS=TEST %CMAKE_ARGS% ..
  - cmake --build .
  - cd %CONFIGURATION%
  - ElonaFoobar.exe

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mv bin\%CONFIGURATION% bin\ElonaFoobar
  - mv CHANGELOG*.md bin\ElonaFoobar
  - mv README*.md bin\ElonaFoobar
  - mv LICENSE bin\ElonaFoobar
  - del bin\ElonaFoobar\*.ilk
  - del bin\ElonaFoobar\*.pdb
  - rd /q /s bin\ElonaFoobar\graphic
  - rd /q /s bin\ElonaFoobar\map
  - rd /q /s bin\ElonaFoobar\original
  - rd /q /s bin\ElonaFoobar\sound
  - rd /q /s bin\ElonaFoobar\user
  - rd /q /s bin\ElonaFoobar\tests
  - rd /q /s bin\ElonaFoobar\tmp
  - cd bin
  - 7z a ElonaFoobar-windows.zip ElonaFoobar

artifacts:
  - path: ElonaFoobar-windows.zip
